app_name=my-react-demo-app
port=3000

start-server:
	npm run start

install-dependencies:	
	npm i -D react react-dom @types/react @types/react-dom @fontsource/roboto @mui/material @emotion/react @emotion/styled @mui/styled-engine-sc styled-components @mui/icons-material
	
