up:
	sudo docker-compose up --build -d 
	sleep 30
	google-chrome http://localhost:5601

down:
	sudo docker-compose down
# about low virtual memory run for current terminal only:
# sysctl -w vm.max_map_count=262144op